### ISSUE TITLE
How to start a Unit test and E2E

### ISSUE THREAD

**Issue by raja-prog** [ixartz/Next-js-Boilerplate#117]
I couldn't understand how to work with Cypress and JEST. help would be appreciated

**Comment by ixartz** [comment]
For unit testing with Jest, you just need to run `npn run test` and for e2e testing with Cypress, `npm run e2e:headless`

**Comment by raja-prog** [comment]
why we need  to mock `next/router`? @ixartz

**Comment by ixartz** [comment]
Mocking `next/router` is needed to avoid errors when running tests.
