### ISSUE TITLE
Type error: The inferred type of 'MainWithHomeLink' cannot be named without a reference to '.pnpm/@storybook+types@7.0.9/node_modules/@storybook/types'. This is likely not portable. A type annotation is necessary.

### ISSUE THREAD

**Issue by sumantaparida** [ixartz/Next-js-Boilerplate#129]
- When i build facing this
`Type error: The inferred type of 'MainWithHomeLink' cannot be named without a reference to '.pnpm/@storybook+types@7.0.9/node_modules/@storybook/types'. This is likely not portable. A type annotation is necessary.`

**Comment by sumantaparida** [comment]
<img width="684" alt="Screenshot 2023-05-28 at 4 00 54 PM" src="https://github.com/ixartz/Next-js-Boilerplate/assets/7557790/dcaba2f3-5275-4e98-90cb-807a0f3ceef0">

**Comment by ixartz** [comment]
@sumantaparida Could you share more information on how we can reproduce? Because, the error is in folder .pnpm, the project doesn't use pnpm by default. Then, in the screenshot, the command `yarn build`, it uses yarn.

For your information, the default package manager is `npm` because it provides the package-lock.json file.

**Comment by sumantaparida** [comment]
> @sumantaparida Could you share more information on how we can reproduce? Because, the error is in folder .pnpm, the project doesn't use pnpm by default. Then, in the screenshot, the command `yarn build`, it uses yarn.
> 
> For your information, the default package manager is `npm` because it provides the package-lock.json file.

Issues is resolved, Resion behind this is the type of error
`export const MainWithHomeLink: Story = {}`
try this

**Comment by ixartz** [comment]
@sumantaparida I don't 100% understand the fix, is it possible to create a PR? So, I can see it in context and I can even merge the PR.

Thanks in advance.

**Comment by sumantaparida** [comment]
Hi @ixartz 
When I clone this and run this cmd
1: yarn install
2: yarn build
then I face this
<img width="1405" alt="Screenshot 2023-05-29 at 8 13 02 PM" src="https://github.com/ixartz/Next-js-Boilerplate/assets/7557790/9fb84630-2907-4b31-99fa-2809cb7ba3df">

===
this is the changes
```
export const MainWithHomeLink: Story = {
  play: async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const loginButton = await canvas.getByRole('link', {
      name: /Home/i,
    });

    await userEvent.click(loginButton);
  },
} satisfies Story;
```
