### ISSUE TITLE
Next 18 n or i18n

### ISSUE THREAD

**Issue by ShintaroNippon** [ixartz/Next-js-Boilerplate#13]
Hi there. Thanks by the boilerplate.
It is possible to add multi language? 
Next 18 n or i18n
And add redux or I should I use context API?

Thanks in advance
Best Shintaro

**Comment by ixartz** [comment]
Hi @ShintaroNippon,

It's something I want to add the multi language.

Now, most of time I suggest context API instead of Redux. But, it's totally based on you context, sometime you need to continue using Redux.

Thanks.

**Comment by resatyildiz** [comment]
Hi @ixartz,

In my opinion we must add Multi Language infrastructure as base feature in this project so this project will be useful for people. And I want contribute to this project with this feature infrastructure..

Thanks.

**Comment by ixartz** [comment]
Totally agree with @resatyildiz, it's definitively useful to add it as a base feature. I'm currently focusing on the testing part by adding Jest, Cypress, etc. As an indie developer, my resources are limited. So, all help are welcome for multi language.

**Comment by ixartz** [comment]
I see some library doing the opposite: implementing i18n in `next export` but breaking other features.

**Comment by sunxyw** [comment]
I'm using ParaglideJS as an i18n solution in my personal project, maybe you could see if it's suitable to be included in this boilerplate.

Documentation: https://inlang.com/m/gerre34r/library-inlang-paraglideJs
How to integrate into App Router: https://inlang.com/g/wxcebbig/guide-lorissigrist-useParaglideJsWithNextjsAppRouter
Page Router: https://inlang.com/g/uxohikde/guide-lorissigrist-useParaglideJsWithNextjsPagesRouter
