### ISSUE TITLE
Migrate from Cypress to Playwright

### ISSUE THREAD

**Issue by kaushalyap** [ixartz/Next-js-Boilerplate#133]

**Comment by ixartz** [comment]
@kaushalyap Thank you for your suggestion. Is it any reason to switch from Cypress to Playwright.

Is it something we can do in Playwright but cannot with Cypress? Actually, I've never tried Playwright before.

**Comment by ixartz** [comment]
@kaushalyap

https://www.reddit.com/r/QualityAssurance/comments/12by82p/cypress_vs_playwright/jf1hqd7/

This is also true with Cypress, it also work like this

I read the [Reddit thread](https://www.reddit.com/r/QualityAssurance/comments/12by82p/cypress_vs_playwright/), I just feel it's a comparison between Emacs and VIM. Both has advantages and disadvantages.

I would try Playwright, but not 100% convinced yet.

**Comment by ixartz** [comment]
I'm currently working to add Playwright instead of Cypress: https://github.com/ixartz/Next-js-Boilerplate/pull/173

**Comment by ixartz** [comment]
Next.js Boilerplate now uses Playwright instead of Cypress, I just merged the PR: https://github.com/ixartz/Next-js-Boilerplate/pull/173
