### ISSUE TITLE
Google Analytic 

### ISSUE THREAD

**Issue by yudataguy** [ixartz/Next-js-Boilerplate#140]
added https://npmjs.com/package/nextjs-google-analytics, but getting error when adding to `page.jsx`, under `return <>` 

```
<GoogleAnalytics trackPageViews gaMeasurementId="G-XYZ" />
```

any suggestion on where should it be placed instead?

**Comment by ixartz** [comment]
Not really sure this is related to the boilerplate. The boilerplate didn't do anything special and you shouldn't getting error.
