### ISSUE TITLE
Building Failed

### ISSUE THREAD

**Issue by rick1day** [ixartz/Next-js-Boilerplate#162]
How i can resolve this ?

8:42:04 AM: Netlify Build                                                 
8:42:04 AM: ────────────────────────────────────────────────────────────────
8:42:04 AM: ​
8:42:04 AM: ❯ Version
8:42:04 AM:   @netlify/build 29.20.11
8:42:04 AM: ​
8:42:04 AM: ❯ Flags
8:42:04 AM:   baseRelDir: true
8:42:04 AM:   buildId: 64f2caf35cc9ab448545aad2
8:42:04 AM:   deployId: 64f2caf35cc9ab448545aad4
8:42:04 AM: ​
8:42:04 AM: ❯ Current directory
8:42:04 AM:   /opt/build/repo
8:42:04 AM: ​
8:42:04 AM: ❯ Config file
8:42:04 AM:   /opt/build/repo/netlify.toml
8:42:04 AM: ​
8:42:04 AM: ❯ Context
8:42:04 AM:   production
8:42:04 AM: ​
8:42:04 AM: ❯ Installing plugins
8:42:04 AM:    - @netlify/plugin-nextjs@4.40.1
8:42:20 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
8:42:16 AM: ​
8:42:16 AM: ❯ Using Next.js Runtime - v4.40.1
8:42:17 AM: ​
8:42:17 AM: @netlify/plugin-nextjs (onPreBuild event)                     
8:42:17 AM: ────────────────────────────────────────────────────────────────
8:42:17 AM: ​
8:42:17 AM: No Next.js cache to restore.
8:42:17 AM: Netlify configuration property build.environment.NEXT_PRIVATE_TARGET value changed.
8:42:17 AM: ​
8:42:17 AM: (@netlify/plugin-nextjs onPreBuild completed in 47ms)
8:42:17 AM: ​
8:42:17 AM: build.command from netlify.toml                               
8:42:17 AM: ────────────────────────────────────────────────────────────────
8:42:17 AM: ​
8:42:17 AM: $ npm run build
8:42:17 AM: > next-js-boilerplate@3.20.0 build
8:42:17 AM: > npm run db:migrate && next build
8:42:17 AM: > next-js-boilerplate@3.20.0 db:migrate
8:42:17 AM: > tsx ./scripts/DbMigrate.ts
8:42:18 AM: Migration started
8:42:18 AM: Migration failed
8:42:18 AM: LibsqlError: URL_INVALID: The URL is not in a valid format
8:42:18 AM:     at parseUri (/opt/build/repo/node_modules/@libsql/client/lib-cjs/uri.js:12:15)
8:42:18 AM:     at expandConfig (/opt/build/repo/node_modules/@libsql/client/lib-cjs/config.js:13:30)
8:42:18 AM:     at createClient (/opt/build/repo/node_modules/@libsql/client/lib-cjs/node.js:28:42)
8:42:18 AM:     at main (/opt/build/repo/scripts/DbMigrate.ts:9:18)
8:42:18 AM:     at <anonymous> (/opt/build/repo/scripts/DbMigrate.ts:23:1)
8:42:18 AM:     at Object.<anonymous> (/opt/build/repo/scripts/DbMigrate.ts:27:2)
8:42:18 AM:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
8:42:18 AM:     at Object.F (/opt/build/repo/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
8:42:18 AM:     at Module.load (node:internal/modules/cjs/loader:1119:32)
8:42:18 AM:     at Module._load (node:internal/modules/cjs/loader:960:12) {
8:42:18 AM:   code: 'URL_INVALID',
8:42:18 AM:   [cause]: undefined
8:42:18 AM: }
8:42:18 AM: ​
8:42:18 AM: build.command failed                                        
8:42:18 AM: ────────────────────────────────────────────────────────────────
8:42:18 AM: ​
8:42:18 AM:   Error message
8:42:18 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
8:42:18 AM: ​
8:42:18 AM:   Error location
8:42:18 AM:   In build.command from netlify.toml:
8:42:18 AM:   npm run build
8:42:18 AM: ​
8:42:18 AM:   Resolved config
8:42:18 AM:   build:
8:42:18 AM:     command: npm run build
8:42:18 AM:     commandOrigin: config
8:42:18 AM:     environment:
8:42:18 AM:       - NEXT_PRIVATE_TARGET
8:42:18 AM:     publish: /opt/build/repo/.next
8:42:18 AM:     publishOrigin: config
8:42:18 AM:   plugins:
8:42:18 AM:     - inputs: {}
8:42:18 AM:       origin: ui
8:42:18 AM:       package: '@netlify/plugin-nextjs'
8:42:20 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:42:20 AM: Failing build: Failed to build site
8:42:20 AM: Finished processing build request in 1m9.026s

**Comment by ixartz** [comment]
Your build indicates an error:

8:42:18 AM: LibsqlError: URL_INVALID: The URL is not in a valid format

URL is defined by DATABASE_URL

**Comment by ixartz** [comment]
@rick1day Thank you for reporting your issue. I took the opportunity to update the README file: https://github.com/ixartz/Next-js-Boilerplate/blob/main/README.md#deploy-to-netlify

It should help other developers to avoid the error.
