### ISSUE TITLE
Difficulty Using Template and Running Migrations on Vercel Deploy

### ISSUE THREAD

**Issue by Canopix** [ixartz/Next-js-Boilerplate#163]
Hello,

I'm having trouble understanding how to use the provided template, especially when it comes to populating the database and running migrations.

Details:

I've successfully deployed my app on Vercel.
I'm unsure about how to execute new migrations during each build on Vercel.
Questions:

Can someone provide a step-by-step guide on how to use the template to populate the database?
How can I ensure that new migrations are executed during each build on Vercel?
Any help or guidance would be greatly appreciated. Thank you!

**Comment by ixartz** [comment]
@Canopix For the database, the template uses Drizzle ORM. You can find all the information on how to populate and run the migration by looking in the official documentation: https://orm.drizzle.team/docs/quick-start

By default, a new migration is executed before building and deploying to Vercel: https://github.com/ixartz/Next-js-Boilerplate/blob/main/package.json#L6
