### ISSUE TITLE
Headless ui not working with this boilerplate when updating to react 18

### ISSUE THREAD

**Issue by lveillard** [ixartz/Next-js-Boilerplate#17]
Hello all!
I'm using this boilerplate (excellent job btw) and i'm unable to make headlessUI work with it when upgrading to react 18.

In this codesandbox, the toggle works as expected:
https://codesandbox.io/s/winter-waterfall-qmxf7?file=/pages/index.js

But if you follow the following steps, it does not:

1) clone https://github.com/ixartz/Next-js-Boilerplate

2) yarn add @headlessui/react@next

3) Add this somewhere in the index page

```
  const [isShowing, setIsShowing] = useState(false)
 ....

        <button onClick={() => setIsShowing((isShowing) => !isShowing)}>
          Toggle
        </button>

        <Transition show={isShowing}>I will appear and disappear.</Transition>    
```

4) Test the toggle => it works
5) update to react 18 beta => yarn add react-dom@next; yarn add react@next
6) Now toggle does not work

Thanks!

**Comment by ixartz** [comment]
Hello @lveillard,

This is something not related specifically to the boilerplate. It mostly related to headless UI and React 18.

Thanks.

**Comment by lveillard** [comment]
Hello @ixartz !
I thought it was the case but it seems it is not, a code sandbox with same versions of next, headlessui and react works properly:

https://codesandbox.io/s/winter-waterfall-qmxf7?file=/pages/index.js

But if you follow the steps here and you add headlessui to the boilerplate, is not working. Spent a lot of hours trying to find out why, but seems to be specific to some configuration here

**Comment by ixartz** [comment]
React 18 is in beta and the version of headless UI you are using is also in beta.

Please use the React 17 and headless UI version 1.4.2.

**Comment by lveillard** [comment]
In the sandbox i've shared before, none of the versions are in beta, React 18 is in rc, and headless ui 1.4.2 is the last stable version. And it's working properly. You can toggle the button.

I think the problem is that the issue affects only the dev environment, and i guess codesandbox is doing something that dodges the error. If anyone gets to this post, feel free to use suspense and lazyload with react 18.
