### ISSUE TITLE
Migrating to Vitest

### ISSUE THREAD

**Issue by kaushalyap** [ixartz/Next-js-Boilerplate#174]
It seems you recently start working on Playwright migration, which is great!

Next migration is to migrate from Jest to Vitest, since Vitest is reaching 1.0, currently in [v1 beta](https://github.com/vitest-dev/vitest/releases/tag/v1.0.0-beta.1)

**Comment by ixartz** [comment]
Why Vitest?

Next.js has a built-in configuration for Jest, which is not the case with Vitest if not wrong?

I can understand we can use Vitest with Vite but Next.js is not build on top of Vite. Love to hear any feedback and suggestion.

What bring Vitest compared to Jest?

**Comment by kaushalyap** [comment]
https://vitest.dev/guide/comparisons.html#jest

Mainly for performance reasons, faster test suits means faster feedback loop which means improved DX.

**Comment by ixartz** [comment]
The default configuration provided by Next.js for Jest use @swc/jest behind the scene, should provide a good performance.

Based on some reddit post, Vitest is even slower: https://www.reddit.com/r/reactjs/comments/1066fvv/test_runner_spa_vite_react_vitest_vs_jestswc/?rdt=41518

**Comment by ixartz** [comment]
Here is another post about the performance: https://www.jameslmilner.com/posts/speeding-up-typescript-jest-tests/

**Comment by ixartz** [comment]
@kaushalyap The project is now using Vitest for testing instead of Jest, thank you so much for the suggestion

https://github.com/ixartz/Next-js-Boilerplate/pull/280

Better DX compared to Jest and less configuration
