### ISSUE TITLE
Sign-up and Sign-in meta descriptions should be swapped

### ISSUE THREAD

**Issue by yfenes** [ixartz/Next-js-Boilerplate#185]
Sign-up description says "sign in"
Sign-in description says "create an account"

I think they should be swapped.

https://github.com/ixartz/Next-js-Boilerplate/blob/fa73c81745f13c43c28d1d4c72ba7763c2b72613/src/app/(auth)/(center)/sign-up/%5B%5B...sign-up%5D%5D/page.tsx#L5-L8

https://github.com/ixartz/Next-js-Boilerplate/blob/fa73c81745f13c43c28d1d4c72ba7763c2b72613/src/app/(auth)/(center)/sign-in/%5B%5B...sign-in%5D%5D/page.tsx#L5-L8

**Comment by ixartz** [comment]
@yfenes Thank you for reporting, it's now fixed.
