### ISSUE TITLE
 Add `.devcontainer/devcontainer.json

### ISSUE THREAD

**Issue by PriyansuMaurya** [ixartz/Next-js-Boilerplate#186]
- A `devcontainer.json` file can **install tools and runtimes**, and perform **other setup tasks** that the project requires.
- It **installs all dependencies** and **runs the project automatically**, allowing the developer to **focus on coding**.
- As the project is a Boilerplate with Tailwind CSS, TypeScript, and Prettier, this file can install all of the required extensions in a matter of seconds.
- A `devcontainer.json` file can be used to configure the development container for both codespaces and local development using Visual Studio Code.

You can try how it works by creating a codespace on the **main** branch in this repository.

![image](https://github.com/priyankarpal/ProjectsHut/assets/101447544/e6a0289a-420d-4e07-8619-fb9dffc56f82)

Here is the link to the repository: https://github.com/PriyansuMaurya/Rick-and-Morty-App

**Comment by ixartz** [comment]
I have never try it but I think it can be great to add it into the boilerplate.

How about stackblitz, codepen, replit, etc.?

**Comment by PriyansuMaurya** [comment]
> How about stackblitz, codepen, replit, etc.?


They are also great option but I've never seen anyone doing contribution from the same, as you know codespaces provide a native support of vscode which is great for everyone.

**Comment by ixartz** [comment]
Yes, the native support for vscode and github is great

**Comment by Geczy** [comment]
is there a pr for this?

**Comment by ixartz** [comment]
For feature suggestion, we'll use the project to track the update: https://github.com/users/ixartz/projects/1

I've added this issue into the Roadmap
