### ISSUE TITLE
 Image quality

### ISSUE THREAD

**Issue by KesleyDavid** [ixartz/Next-js-Boilerplate#187]
Looking at the example link, the image looks great and of high quality, but when I download the code, the image is of terrible quality.

Does anyone know what it could be?
Am I missing something when I do my deployment?

[https://creativedesignsguru.com/demo/Nextjs-Boilerplate/](https://creativedesignsguru.com/demo/Nextjs-Boilerplate/)
![Screenshot from 2023-11-07 18-17-24](https://github.com/ixartz/Next-js-Boilerplate/assets/39314443/48995e98-3c4d-4b4e-afdf-74cf8e2d647a)

`localhost`
![Screenshot from 2023-11-07 18-17-34](https://github.com/ixartz/Next-js-Boilerplate/assets/39314443/ec7e4aa5-cafb-4ab4-9be1-18bd7e9a193b)

**Comment by ixartz** [comment]
The old image is not optimized, this is why the image quality is better. The second image is optimized by Next.js/image component, this is why the quality is lower.

I didn't take the time to improve the quality for the second one, I just use the default configuration. It should have some configuration to improve the image quality of the second image.

I'm totally open to suggestion to improve the second image.

**Comment by KesleyDavid** [comment]
> The old image is not optimized, this is why the image quality is better. The second image is optimized by Next.js/image component, this is why the quality is lower.
> 
> I didn't take the time to improve the quality for the second one, I just use the default configuration. It should have some configuration to improve the image quality of the second image.
> 
> I'm totally open to suggestion to improve the second image.

Thank you for the explanation.

I was researching, and found a way in the documentation, to use the image component and also maintain quality, using quality={100} (but it's still a little blurry) and also unoptimized (the image is in complete quality))

Maybe it would be good to add it to the code, so users like me can understand if they want it optimized or not, what do you think?

If you prefer, I can create a PR with the modification

**Comment by ixartz** [comment]
@KesleyDavid Thank you for your research, I'm totally open to increase the image quality and open to PR for modification.
