### ISSUE TITLE
Custom SignOutButton currently not being used

### ISSUE THREAD

**Issue by MateusSantosFonseca** [ixartz/Next-js-Boilerplate#189]
It's not necessarily a bug but:

On **src/app/(auth)/dashboard/layout.tsx** I _think_ that the SignOutButton shouldn't be imported directly from Clerk

`import { SignOutButton } from '@clerk/nextjs';*`

because in the project there's a custom **SignOutButton** _(currently unused)_ that imports from Clerk 

**src\components\SignOutButton.tsx**.

I noticed that while making some changes to the button. Just wanted to point that out!

**Comment by ixartz** [comment]
@MateusSantosFonseca Thank you for reporting it, love your feedback. I don't remember what I was trying to do😅 I'll investigate but definitively, something can be improved.

**Comment by ixartz** [comment]
@MateusSantosFonseca You really made my day! Always appreciate all feedback to improve the boilerplate. On top of that, you made sponsor 🙏

**Comment by ixartz** [comment]
@MateusSantosFonseca Now, the project is using the custom button and to avoid confusion, I also took the opportunity to rename to LogOutButton

PR: https://github.com/ixartz/Next-js-Boilerplate/pull/190

**Comment by MateusSantosFonseca** [comment]
Thanks, your boilerplate is really helpful! Glad I helped a little bit. Have a great week! =]

**Comment by ixartz** [comment]
You too, have a great week!
