### ISSUE TITLE
Mark repo as template repository?

### ISSUE THREAD

**Issue by jsjoeio** [ixartz/Next-js-Boilerplate#2]
Hey! Thanks for making this :) 

Would it make sense to mark this as a [template repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)?

**Comment by ixartz** [comment]
Hey @jsjoeio, you're welcome. Sorry for this late response, I didn't get any notification when you've shared your GitHub issue. Apparently, I didn't enable the feature for this repo. Luckily, I was updating the repo to Next 10 and see your comment.

It makes sense to use a template repository. Actually, in the past, the repo was a template but there is some drawback: it's impossible to track the number of people using the template.

By making a normal repository (not a template), people tend to fork the repo and you get a little nice counter of fork :)

PS: Don't take this statement as truth: I've just noticed it with my GitHub repositories and not confirmed by other developers.

**Comment by jsjoeio** [comment]
No worries at all! Ah, that makes sense. I'd want to know that metric too. Well feel free to close this then :)
