### ISSUE TITLE
 Error: Cannot find module './sw.js.json'

### ISSUE THREAD

**Issue by consciouscoder** [ixartz/Next-js-Boilerplate#218]
Any idea how to fix this error? I just cloned the repo and got this in the console repeatedly

 ⨯ Error: Cannot find module './sw.js.json'
    at /Users/dladendorf/workspace/web3/fivestarscard/.next/server/app/[locale]/(auth)/(center)/sign-up/[[...sign-up]]/page.js:34:12
    at async eval (./src/libs/i18n.ts:17:20)
    at async Module.generateMetadata$1 (page.tsx:28:15)

**Comment by ixartz** [comment]
It's the first time I'm seeing the error. Could you share with me more context about the error? What command did you run? What OS and what node version you are using?

**Comment by consciouscoder** [comment]
Error seems to be gone now, once I setup Clerk auth. I believe it may be related to not having the Clerk keys in the .env files.

**Comment by ixartz** [comment]
It's very strange, not having the Clerk keys shouldn't generate the error.

The boilerplate should still work even the Clerk key is not defined.

**Comment by ixartz** [comment]
Could you remove the Clerk key and see if the problems is still here?
