### ISSUE TITLE
add additional authentication options (not just clerk)

### ISSUE THREAD

**Issue by Geczy** [ixartz/Next-js-Boilerplate#222]
clerk has a max users of 10k, i recommend adding nextauth to keep closer with the nextjs ecosystem and allow you to bypass the clerk limits

**Comment by ixartz** [comment]
Thank you for suggesting, totally open to PR for nextauth.

It would even be greater if you can choose the auth provider like Supabase, Nextauth, Clerk, and more. An adapter would be awesome.

**Comment by sandercoffee** [comment]
Auth.js (nextAuth) <3

**Comment by Geczy** [comment]
was it added? @ixartz

**Comment by ixartz** [comment]
For feature suggestion, we'll use the project to track the update: https://github.com/users/ixartz/projects/1

**Comment by page-fault-in-nonpaged-area** [comment]
Would love to see this as well. Next 12 was easy as nearly drag & drop; Next 14 with the app router is very confusing thus far.

**Comment by Nudelsalad** [comment]
Has someone successfully used auth.js with the boilerplate and wants to share his code 😄

**Comment by NothingHollow** [comment]
> Has someone successfully used auth.js with the boilerplate and wants to share his code 😄

It takes 15 mins ish to setup tbh
