### ISSUE TITLE
Getting End of line error Prettier ESLint

### ISSUE THREAD

**Issue by max-programming** [ixartz/Next-js-Boilerplate#23]
Everything works fine when I run the project but in VS Code I get this error for endofline with prettier on Windows
![image](https://user-images.githubusercontent.com/51731966/158942729-635f8b5f-822a-4b1c-b9e5-98e4ba28fb0f.png)

**Comment by ixartz** [comment]
You can find the answer on StackOverflow: https://stackoverflow.com/a/54209946

**Comment by ixartz** [comment]
@max-programming Does this pull request solve your issue? https://github.com/ixartz/Next-js-Boilerplate/pull/24

Could you make a fresh and clean git clone? And try this pull request. Does it solve your issue? I don't have a Windows.
