### ISSUE TITLE
Guide to remove certain dependencies?

### ISSUE THREAD

**Issue by txfs19260817** [ixartz/Next-js-Boilerplate#242]
Hey there, thank you for the great boilerplate! It's a really comprehensive starter though, I am looking to customize it by removing or replacing certain components. Some dependencies appear to be coupled with GitHub Actions or configs, making them hard to remove with simply npm uninstall. A guide on removing these dependencies would be greatly appreciated. Thank you!

**Comment by ixartz** [comment]
Hi @txfs19260817, thank you for your comment. If one dependencies is used in GitHub Actions or configs, you just need to remove with npm uninstall and remove the mention in GitHub Actions or configs. All the dependencies should be easy to remove.

Indeed, it could be great to have a clear documentation but it shouldn't be blocking.

**Comment by ixartz** [comment]
For feature suggestion, we'll use the project to track the update: https://github.com/users/ixartz/projects/1

I've added this issue into the Roadmap
