### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by TungNguyenDocosan** [ixartz/Next-js-Boilerplate#260]
Currently your sitemap is not working well, please check it again

**Comment by ixartz** [comment]
Indeed, the automatic sitemap is not working well. For the time being, you can still use: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap, but you need to manually define it.

**Comment by TungNguyenDocosan** [comment]
This is so bad that it's still unfinished.

**Comment by ixartz** [comment]
The project is totally open to contribution, you can make a PR to fix the issue. I'm happy to merge it.

For your reference, the automatic sitemap is the cherry on the cake. The official way to do it is the manual process: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

**Comment by TungNguyenDocosan** [comment]
If it has to be done manually, I think you should leave the next-sitemap library out of your project

**Comment by ixartz** [comment]
As you suggested, `next-sitemap` has been removed and the project now use the official way.

Maybe it'll add it back if it's working properly with i18n for an automatic sitemap.xml and robots.txt

**Comment by TungNguyenDocosan** [comment]
Good job bro

**Comment by ixartz** [comment]
The project follows the official Next.js way to generate Sitemap: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

You can find all the information on the official documentation.
