### ISSUE TITLE
[QUESTION} - How to prevent ESLint errors from stopping deployment process

### ISSUE THREAD

**Issue by max-programming** [ixartz/Next-js-Boilerplate#29]
I recently got into a problem where my website wasn't going live because of this ESLint formatting error. Is there a way to prevent this in production and deployment process and keep the settings on in the development process?

![image](https://user-images.githubusercontent.com/51731966/163898918-e1a868f3-a819-45ee-9084-698dc4a3c195.png)

**Comment by ixartz** [comment]
@max-programming, it's a formatting issue. Why you don't solve it? Most of the formatting issue can automatically be solved, no need to manually formatting. The project provides VSCode extension and settings to automatically solve the issue on Save.

**Comment by max-programming** [comment]
@ixartz Yes you're right I did format the code later. But for some reason (due to my slow system) it didn't format that particular file. And that affected the deployment.

I really like the way formatting is approached in this template and it's absolutely the best. But I just want to remove the checks for deployment if it's possible because then by mistake if a file doesn't get formatted then I would have to manually check each deployment

**Comment by ixartz** [comment]
Here is the solution to disable linter for production: https://nextjs.org/docs/api-reference/next.config.js/ignoring-eslint

I have never tried it. It's a Next.js built-in feature.

**Comment by max-programming** [comment]
Thanks for helping out!

**Comment by max-programming** [comment]
Thanks for helping out!
