### ISSUE TITLE
Improvement:  "Follow @Ixartz on Twitter" button and text is too small

### ISSUE THREAD

**Issue by Lavavarshney** [ixartz/Next-js-Boilerplate#293]
![image](https://github.com/user-attachments/assets/84bc6c07-0967-4c63-8cca-6b8f9e0e0575)

**Comment by ixartz** [comment]
Thank you for your suggestion. Yes, I can try to make the follow button a little bit bigger.

**Comment by ixartz** [comment]
Done. Thank you for reporting it!
