### ISSUE TITLE
BUG: The  background colour on hovering above "Star On Github" is too light

### ISSUE THREAD

**Issue by Lavavarshney** [ixartz/Next-js-Boilerplate#294]
![image](https://github.com/user-attachments/assets/7fe852e9-c577-4902-845a-3ba3b4af083f)

**Comment by ixartz** [comment]
This should be a default behavior from Shadcn UI. In the project, usually we keep the default behavior.

<img width="282" alt="image" src="https://github.com/user-attachments/assets/5b295bb5-c6d3-484a-8ba6-313394e142c7">
