### ISSUE TITLE
Storybook error with latest NextJS 15 release and React 19 RC

### ISSUE THREAD

**Issue by mzavattaro** [ixartz/Next-js-Boilerplate#322]
There's a dependency conflict between Storybook, NextJS 15 and React 19 RC:
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/fad2e2fd-8b17-430c-821d-0f0fa8e7abf1">

Just flagging for future bug fixing.

**Comment by ixartz** [comment]
Unfortunately, I got the same error as you. I also wanted to update to Next.js 15 and React 19 RC.

But, it seems we need to wait Storybook support. Maybe also other dependencies.

We should be able to track the progress here: https://github.com/storybookjs/storybook/issues/29421

**Comment by ixartz** [comment]
For reference, Next.js 15 introduce new bugs: https://github.com/amannn/next-intl/issues/1442

**Comment by mzavattaro** [comment]
Good to know, seems like they've got a fair bit of cleaning up to do.

**Comment by ixartz** [comment]
It's a really big update and a lot of breaking changes.

Even if the project doesn't use Shadcn UI, I also hear there are a lot of issue with Shadcn UI.

Definitively, not a smooth update 😢

**Comment by ixartz** [comment]
Just migrate to Next.js 15 and React 19 RC: https://github.com/ixartz/Next-js-Boilerplate/pull/327, supporting the same features as Next.js 14
