### ISSUE TITLE
Live reload does not work

### ISSUE THREAD

**Issue by pdwalker30** [ixartz/Next-js-Boilerplate#40]
I forked the repo.  Node version 16.15, npm version 8.5.5, Windows 10 Home, any browser, can't think of any other relevant info to give you.

Clone the repo, npm install, npm build, npm run start -
Webapp comes up on localhost:3000.  Altered some text in the HTML, saved it to verify hot reload works.  Text never updates.  Refresh page, no update.  The only way to get the page to update is to rebuild the app.

Am I missing something?  Is there a config setting where I need to change it to do hot reloads or something?

**Comment by pdwalker30** [comment]
use command npm run dev.  Also, if you have having issues, delete the .next folder, then run npm run dev

**Comment by ixartz** [comment]
Thank you @pdwalker30 for sharing the solution.
