### ISSUE TITLE
Use getLayout function to customize layout

### ISSUE THREAD

**Issue by riolly** [ixartz/Next-js-Boilerplate#43]
As it's written on the official [docs](https://nextjs.org/docs/basic-features/layouts#per-page-layouts).

```
// pages/index.js

import Layout from '../components/layout'
import NestedLayout from '../components/nested-layout'

export default function Page() {
  return {
    /** Your content */
  }
}

Page.getLayout = function getLayout(page) {
  return (
    <Layout>
      <NestedLayout>{page}</NestedLayout>
    </Layout>
  )
}
```

```
// pages/_app.js

export default function MyApp({ Component, pageProps }) {
  // Use the layout defined at the page level, if available
  const getLayout = Component.getLayout || ((page) => page)

  return getLayout(<Component {...pageProps} />)
}
```

**Comment by ixartz** [comment]
@riolly, this also something I use personally but I didn't integrate it. Should we?

**Comment by riolly** [comment]
We use that pattern to avoid rerendering the layout component when navigating to a page with the same layout. (mimicking client-side navigation)
And I think those who use this template have been familiar with next.js and (the other tech stack inside it) and will end up in that situation also.

**Comment by Dannymx** [comment]
I think the `getLayout` pattern should be implemented.

**Comment by ixartz** [comment]
I think we can directly switch to the `app` directory when the feature come out from the beta and there are still some missing feature: https://beta.nextjs.org/docs/app-directory-roadmap#planned-features

Hope the beta won't last too long.

**Comment by ixartz** [comment]
Planning to switch directly to `app` directory when the feature come out from the beta.
