### ISSUE TITLE
Can't lint .tsx files

### ISSUE THREAD

**Issue by znat** [ixartz/Next-js-Boilerplate#53]
Hi, thanks a lot for this boilerplate.
It works great except (at least for me) for validating/linting .tsx files.
The code compiles fine but I have a lot of inconsistent errors, here's an example:

![image](https://user-images.githubusercontent.com/3694634/185083230-59a9adee-68d7-4c4a-b8f0-a2280fd778c0.png)

Wondering if you had any pointers on how to solve this?
Thanks!

**Comment by ixartz** [comment]
This isn't a ESLint error (linter), it's a compilation error with TypeScript.
Whether you've changed the TypeScript default configuration or you code is incorrect in TypeScript.

**Comment by znat** [comment]
The code compiles fine and the app works as expected so I suspect it's not a true compiler error but rather something raised by eslint inside VSCode.

both `.eslintrc` and `tsconfig.json` are unchanged.

All tokens have their own errors:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/3694634/185373558-db8cfbbe-a05f-4ac3-9643-2f2e88cf8e8b.png">

<img width="525" alt="image" src="https://user-images.githubusercontent.com/3694634/185373446-13fc3980-fbce-4148-b706-350dcbbcaec1.png">

If you think of something...

**Comment by ixartz** [comment]
Based on your screenshot, the error code `ts(XXXX)` with a number is related to TypeScript compiler. If it's an ESLint error, it have `eslint(XXXXXXXXX)` as an error code.

Maybe a misconfiguration in VSCode? Some errors with some extension?

**Comment by ixartz** [comment]
Didn't receive any response closing the issue for now.
