### ISSUE TITLE
NextJS 13.0 new 'app' dir feature

### ISSUE THREAD

**Issue by comverser** [ixartz/Next-js-Boilerplate#62]
How about adding `app` dir feature in the future?

**Comment by ixartz** [comment]
I'm currently waiting for `app` dir come out from the beta. But, totally open to suggestion or open to pull request if someone want to try before

`app` dir has still some unimplemented feature: https://beta.nextjs.org/docs/app-directory-roadmap#planned-features

**Comment by comverser** [comment]
Thank you for your answer.

**Comment by MUmer01** [comment]
it's out of beta. It can be implemented now.
