### ISSUE TITLE
Yarn 2+ as a replacement of npm

### ISSUE THREAD

**Issue by comverser** [ixartz/Next-js-Boilerplate#63]
How do you think about replacing npm with Yarn 2+ or Yarn Berry?

I think Yarn 2+ is getting attention and  useful because it lighten node installation process. Please refer [the official doc for Yarn 2+](https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern) for details.

**Comment by ixartz** [comment]
Thank you for making the suggestion @comverser.

Thanks to semantic versoning, it should not have any issue to use yarn. Or, using pnpm (Pnpm is also getting a lot of attention).
You are not forced to use any package manager: npm or yarn or pnpm. All package managers should work with the project.
