### ISSUE TITLE
Nextjs 13 Router

### ISSUE THREAD

**Issue by amazingnerd** [ixartz/Next-js-Boilerplate#64]
This repository is using old routing structure, please update it, thank you in advance!

**Comment by ixartz** [comment]
The boilerplate supports the new routing structure and it should work without any issue. You can use it if your project needs it.

But for your information, the new routing is still is in beta and a lot of feature is not working with he new routing structure: https://beta.nextjs.org/docs/app-directory-roadmap#planned-features

"The app directory is currently in beta and we do not recommend using it in production yet.": https://nextjs.org/blog/next-13#new-app-directory-beta

**Comment by fadhilradh** [comment]
I agree with @ixartz , it would not be wise to update to NextJS 13 `app` based for now, since it is still very new to many developers.

**Comment by MUmer01** [comment]
What about now, it's out of beta and not new anymore.

**Comment by ixartz** [comment]
I'm currently learning this new `app` directory and I'll add support to the boilerplate.

FYI, `pages` directory is not deprecated and still can be used.

**Comment by perezpefaur** [comment]
This app directory is game changer!

**Comment by oliverpatrick** [comment]
I would love to see an approach on the app directory, I find it somewhat verbose and tacky. Is anyone looking to fork this with an approach?

**Comment by ixartz** [comment]
If someone has already an experience with the `app` directory, it would great to see a PR.

**Comment by theodesp** [comment]
> This app directory is game changer!
It definitely isn't and still people are trying to make up their minds about it, but it would be nice to have something concrete as an example.

**Comment by ixartz** [comment]
with @l9c help, the App Router is now added into the boilerplate: https://github.com/ixartz/Next-js-Boilerplate
