### ISSUE TITLE
How do you maximize lighthouse score?

### ISSUE THREAD

**Issue by comverser** [ixartz/Next-js-Boilerplate#65]
I couldn't catch sign of efforts for maximizing lighthouse score as a nonexport view.

Would you please tell me how you have maximized lighthouse score?

**Comment by ixartz** [comment]
Using in export mode can increase your lighthouse score. It can increase tremendously. 

Lighthouse score also take account SEO score in `export` and `non-export`, which the boilerplate try to increase by:
- Adding SEO tags, meta tags, etc.
- Adding favicon

The project also followed best practices and accessibility recommendation to increase the score.

For your information, the project is maintained for 2 years. Over the time, Google has adding new rules in the lighthouse score... The project is open source and open to contribution.
