### ISSUE TITLE
Is it possible to add sitemap and github action folder ? 

### ISSUE THREAD

**Issue by arrofirezasatria** [ixartz/Next-js-Boilerplate#68]
I've implemented the next-sitemap in nextjs 12. I think it needs to be added to complement SEO features. and also folder for github action.

**Comment by ixartz** [comment]
@arrofirezasatria, I also think it's a good idea. But, I've never done it myself. So I'm totally open to pull request, especially if you have already done it.

**Comment by arrofirezasatria** [comment]
Ok,. Il try im currently working on it

**Comment by ixartz** [comment]
Thank you for your PR, @arrofirezasatria.
