### ISSUE TITLE
Unresolved module when using absolute import

### ISSUE THREAD

**Issue by ddsuhaimi** [ixartz/Next-js-Boilerplate#7]
Here's my file structure (I've removed anything that isn't relevant).
```
- src
  - components
    - Some.tsx
  - pages
    - index.tsx 
- tsconfig.json
```
I want to import `Some.tsx` in my `index.ts` using absolute path. In my `tsconfig.json`, I have 

```
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "noUncheckedIndexedAccess": true,

    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowUnreachableCode": false,
    "noFallthroughCasesInSwitch": true,

    "target": "es5",
    "outDir": "out",
    "declaration": true,
    "sourceMap": true,

    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,

    "jsx": "preserve",
    "noEmit": true,
    "isolatedModules": true
  },
  "exclude": ["./out/**/*", "./node_modules/**/*"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],

  // absolute path
  "baseUrl": ".",
  "paths": {
    "@/components/*": ["src/components/*"]
  }
}
```

I import using this is my `index.tsx`
```
import Some from '@/components/Some';
```
and I got module not found error, but this
```
import Some from '../components/Some';
```  
works fine. 

Any idea why?

**Comment by ddsuhaimi** [comment]
Close this because absolute import should be in compilerOptions value.
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "noUncheckedIndexedAccess": true,

    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowUnreachableCode": false,
    "noFallthroughCasesInSwitch": true,

    "target": "es5",
    "outDir": "out",
    "declaration": true,
    "sourceMap": true,

    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "allowJs": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,

    "jsx": "preserve",
    "noEmit": true,
    "isolatedModules": true,

    "baseUrl": ".",
    "paths": {
      "@/components/*": ["src/components/*"]
    }
  },
  "exclude": ["./out/**/*", "./node_modules/**/*"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}

**Comment by ixartz** [comment]
Just my curiosity, does Module path aliases works? When I've tried at the beginning (when the features was released), VSCode lost his auto import feature.

**Comment by ddsuhaimi** [comment]
My vscode version is 1.58.2 and I can confirm auto import feature works. Although I did installed several extensions like what what was suggested in .vscode folder. Maybe that helps with auto import.

**Comment by ixartz** [comment]
Thank you @ddsuhaimi, good to know and I might try again
