### ISSUE TITLE
about the project templates folder confuse

### ISSUE THREAD

**Issue by Alvazz** [ixartz/Next-js-Boilerplate#72]
Sorry, I'm new to nextjs. When I was learning this project, I found that there is a templates directory in the source code, and there is a Main.tsx file under it. What is this templates directory used for? What is this Main.tsx used for? Thank you for your dedication.

**Comment by ixartz** [comment]
Templates are not related to Next.js. I just use it as example, so you can use it or not based on your projects.

In my case, the Main.tsx is shared component between Next.js pages used by the about and index page to have the look and feel.
