### ISSUE TITLE
Boilerplate without Typescript?

### ISSUE THREAD

**Issue by spabolu** [ixartz/Next-js-Boilerplate#92]
Hi there,
Thanks for making this amazing boilerplate for Next.js. Is it possible for you to create one using JavaScript instead? 

Much appreciated

**Comment by ixartz** [comment]
Hi @spabolu,

The project supports JavaScript without any change (but, I didn't try it myself), you should be able to write your code in JavaScript instead TypeScript without any issue. You can totally do it, it shouldn't have any blocker.

The project focus on TypeScript and I also mostly focus on TypeScript.

**Comment by spabolu** [comment]
Ok, thanks!
