### ISSUE TITLE
how to get updates

### ISSUE THREAD

**Issue by gutisalex** [ixartz/Next-js-Boilerplate#98]
hey, I wonder if I have cloned the boilerplate a year ago, how am I getting the latest changes into my own project?

**Comment by ixartz** [comment]
Hey @gutisalex, you just need to pull the newest from the repository with `git pull`.

**Comment by gutisalex** [comment]
ok but I am not gonna work in the same repo... I would probably re-init git and push it into my own repo...

**Comment by ixartz** [comment]
In that case, you can clone directly the repository and you can get a fresh with the latest version of the boilerplate.
